import { redirect } from "next/navigation";
import { Metadata } from "next";
import holidayData from "@/data/static/national-holidays.json";
import { calculateOptimalVacationPlans } from "../../helpers/calculateOptimalVacation";
import CalendarClientLayout from "../../layouts/CalendarClientLayout";
import dayjs from "dayjs";
import dayOfYear from "dayjs/plugin/dayOfYear";
import "dayjs/locale/tr";

dayjs.extend(dayOfYear);
dayjs.locale("tr");

export const metadata: Metadata = {
  title: "Holiday Opportunities",
  description: "Generated by create next app",
};

export default async function CalendarPage({
  params,
}: {
  params: Promise<{ number: string }>;
}) {
  const resolvedParams = await params;
  const number = parseInt(resolvedParams.number, 10);

  if (isNaN(number) || number <= 0 || number > 30) {
    redirect("/");
  }

  const year = 2025;
  const vacationPlans = calculateOptimalVacationPlans(year, number);

  return (
    <CalendarClientLayout
      year={year}
      vacationPlans={vacationPlans}
      holidayData={holidayData}
    />
  );
}
